"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
# The title of the new pull request
"pull_request_title": "feat: New translations for Hunger Games"
# The contents of the pull request
"pull_request_body": "### What\n- Automated pull request pulling in new or updated translations from Crowdin (https://translate.openfoodfacts.org).\n## Checklist\n- [ ] Check that they are no bad translations. If there are, correct them directly in Crowdin so that they are not resynced again. Then you can correct them here as well, or wait 24 hours for the sync to happen automatically.\n- [ ] Put extra attention on Acholi, which is used mistakenly as a sandbox by people discovering the self-service translation button on Open Food Facts\n- [ ] Once you are happy, that automated checks pass, you can approve the PR and merge it.\n### Part of\n- Translations"
# To add labels for created pull request
"pull_request_labels": "translations"
#
# Files configuration
#
"files": [
  {
    "source" : "/src/i18n/common.json",
    "translation" : "/src/i18n/%two_letters_code%.json"
  }
]
