import { OFF_DOMAIN } from "../../const";
import type {
  MaterialOption,
  PresetCombo,
  RecyclingOption,
  ShapeOption,
} from "./types";

const CITEO_BASE = `https://images.${OFF_DOMAIN}/images/icons/packaging-shapes/citeo/light-mode`;
const PACKAGING_LANG_BASE = `https://images.${OFF_DOMAIN}/images/lang/en/packaging`;
const LABELS_LANG_BASE = `https://images.${OFF_DOMAIN}/images/lang`;

// Common shapes with Citeo light-mode SVG icons and friendly emojis
export const COMMON_SHAPES: ShapeOption[] = [
  {
    id: "en:bottle",
    label: "Bottle / Bouteille",
    emoji: "🍾",
    icon: `${CITEO_BASE}/bouteille-1.svg`,
  },
  {
    id: "en:cap",
    label: "Cap / Bouchon",
    emoji: "🧢",
    icon: `${CITEO_BASE}/bouchon-1.svg`,
  },
  {
    id: "en:tray",
    label: "Tray / Barquette",
    emoji: "🍱",
    icon: `${CITEO_BASE}/plat-plateau-barquette-blister-1.svg`,
  },
  {
    id: "en:film",
    label: "Film / Opercule",
    emoji: "🎞️",
    icon: `${CITEO_BASE}/film-film-a-bulle.svg`,
  },
  {
    id: "en:box",
    label: "Box / Boîte / Étui",
    emoji: "📦",
    icon: `${CITEO_BASE}/boite-boitier-1.svg`,
  },
  {
    id: "en:jar",
    label: "Jar / Bocal",
    emoji: "🫙",
    icon: `${CITEO_BASE}/bocal-verre.svg`,
  },
  {
    id: "en:lid",
    label: "Lid / Couvercle",
    emoji: "🔘",
    icon: `${CITEO_BASE}/couvercle-1.svg`,
  },
  {
    id: "en:can",
    label: "Can / Canette",
    emoji: "🥫",
    icon: `${CITEO_BASE}/boite-boitier-2.svg`,
  },
  {
    id: "en:pot",
    label: "Pot (Yogurt / Dessert)",
    emoji: "🥛",
    icon: `${CITEO_BASE}/pot-1.svg`,
  },
  {
    id: "en:bag",
    label: "Bag / Sachet / Pouch",
    emoji: "🛍️",
    icon: `${CITEO_BASE}/sac-sachet-poche-1.svg`,
  },
  {
    id: "en:carton",
    label: "Carton / Brique",
    emoji: "🧃",
    icon: `${CITEO_BASE}/brique-1.svg`,
  },
  {
    id: "en:wrapper",
    label: "Wrapper / Emballage",
    emoji: "🍬",
    icon: `${CITEO_BASE}/stick-1.svg`,
  },
  {
    id: "en:tube",
    label: "Tube",
    emoji: "🧪",
    icon: `${CITEO_BASE}/tube-1.svg`,
  },
  {
    id: "en:cup",
    label: "Cup / Gobelet",
    emoji: "🥤",
    icon: `${CITEO_BASE}/gobelet-1.svg`,
  },
  {
    id: "en:aerosol",
    label: "Aerosol / Spray",
    emoji: "💨",
    icon: `${CITEO_BASE}/aerosol.svg`,
  },
];

// Gentle Materials (Simple, non-intimidating options for everyone)
export const GENTLE_MATERIALS: MaterialOption[] = [
  {
    id: "en:plastic",
    label: "Plastic",
    category: "gentle",
    emoji: "🧴",
    color: "#0288d1",
    badge: "Most Common",
  },
  {
    id: "en:glass",
    label: "Glass",
    category: "glass",
    emoji: "🫙",
    color: "#2e7d32",
    badge: "Verre",
  },
  {
    id: "en:cardboard",
    label: "Cardboard",
    category: "paper",
    emoji: "📦",
    color: "#b08968",
    badge: "Carton",
  },
  {
    id: "en:paper",
    label: "Paper",
    category: "paper",
    emoji: "📄",
    color: "#d4a373",
    badge: "Papier",
  },
  {
    id: "en:metal",
    label: "Metal",
    category: "metal",
    emoji: "🪙",
    color: "#546e7a",
    badge: "Métal",
  },
  {
    id: "en:aluminium",
    label: "Aluminium",
    category: "metal",
    emoji: "🥫",
    color: "#78909c",
    badge: "Alu",
  },
  {
    id: "en:steel",
    label: "Steel",
    category: "metal",
    emoji: "🔩",
    color: "#455a64",
    badge: "Acier",
  },
  {
    id: "en:tetra-pak",
    label: "Tetra Pak / Composite",
    category: "paper",
    emoji: "🧃",
    color: "#f57c00",
    badge: "Brique",
  },
  {
    id: "en:wood",
    label: "Wood / Cork",
    category: "wood",
    emoji: "🪵",
    color: "#8d6e63",
    badge: "Bois / Liège",
  },
];

// Specific Resins & Detailed Material Codes with official icons
export const SPECIFIC_RESINS: MaterialOption[] = [
  {
    id: "en:pet",
    label: "01 PET (Polyethylene terephthalate)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/01-pet.73x90.svg`,
    badge: "01 PET",
    color: "#0288d1",
  },
  {
    id: "en:hdpe",
    label: "02 PE-HD (High-density polyethylene)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/02-pe-hd.73x90.svg`,
    badge: "02 HDPE",
    color: "#039be5",
  },
  {
    id: "en:pvc",
    label: "03 PVC (Polyvinyl chloride)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/03-pvc.73x90.svg`,
    badge: "03 PVC",
    color: "#00acc1",
  },
  {
    id: "en:ldpe",
    label: "04 PE-LD (Low-density polyethylene)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/04-pe-ld.73x90.svg`,
    badge: "04 LDPE",
    color: "#00897b",
  },
  {
    id: "en:pp",
    label: "05 PP (Polypropylene)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/05-pp.73x90.svg`,
    badge: "05 PP",
    color: "#43a047",
  },
  {
    id: "en:ps",
    label: "06 PS (Polystyrene)",
    category: "resin",
    icon: `${PACKAGING_LANG_BASE}/06-ps.73x90.svg`,
    badge: "06 PS",
    color: "#7cb342",
  },
  {
    id: "en:corrugated-cardboard",
    label: "20 PAP (Corrugated cardboard)",
    category: "paper",
    icon: `${PACKAGING_LANG_BASE}/20-pap.73x90.svg`,
    badge: "20 PAP",
    color: "#8d6e63",
  },
  {
    id: "en:steel",
    label: "40 FE (Steel / Acier)",
    category: "metal",
    icon: `${PACKAGING_LANG_BASE}/40-fe.73x90.svg`,
    badge: "40 FE",
    color: "#546e7a",
  },
  {
    id: "en:aluminium",
    label: "41 ALU (Aluminium)",
    category: "metal",
    icon: `${PACKAGING_LANG_BASE}/41-alu.73x90.svg`,
    badge: "41 ALU",
    color: "#78909c",
  },
  {
    id: "en:clear-glass",
    label: "70 GL (Clear glass)",
    category: "glass",
    icon: `${PACKAGING_LANG_BASE}/70-gl.73x90.svg`,
    badge: "70 GL",
    color: "#2e7d32",
  },
];

// Recycling sorting instructions
export const RECYCLING_OPTIONS: RecyclingOption[] = [
  {
    id: "en:recycle",
    label: "Recycle (Yellow bin / Bac de tri)",
    emoji: "♻️",
    color: "success",
    icon: `${CITEO_BASE}/recycler.svg`,
  },
  {
    id: "en:discard",
    label: "Discard / Trash (Bac noir / À jeter)",
    emoji: "🗑️",
    color: "error",
    icon: `${CITEO_BASE}/jeter.svg`,
  },
  {
    id: "en:compost",
    label: "Compostable",
    emoji: "🌱",
    color: "warning",
    icon: `${LABELS_LANG_BASE}/de/labels/ok-compost.90x90.svg`,
  },
  {
    id: "en:deposit",
    label: "Deposit / Consigne (Pfand)",
    emoji: "🔄",
    color: "info",
    icon: `${LABELS_LANG_BASE}/de/labels/einwegpfand.90x90.svg`,
  },
];

// Presets for 1-click bulk packaging ("For the lazy")
export const PRESET_COMBOS: PresetCombo[] = [
  {
    id: "tray_film",
    title: "Tray + Film",
    description: "Prepared meals, fresh meat, cheese, pasta",
    emoji: "🍱",
    badge: "Ready meals",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:tray",
        shapeName: "Tray (Barquette)",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:film",
        shapeName: "Film",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:discard",
        recyclingName: "Discard",
      },
    ],
  },
  {
    id: "plastic_bottle_cap",
    title: "Plastic Bottle + Cap",
    description: "Water, sodas, juice, cooking oil, milk",
    emoji: "🧴",
    badge: "Beverages",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:bottle",
        shapeName: "Bottle",
        material: "en:pet",
        materialName: "Plastic (PET)",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:cap",
        shapeName: "Cap",
        material: "en:hdpe",
        materialName: "Plastic (HDPE)",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "glass_bottle_metal_cap",
    title: "Glass Bottle + Cap",
    description: "Beer, cider, soda, wine with crown or twist cap",
    emoji: "🍾",
    badge: "Beers & Drinks",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:bottle",
        shapeName: "Bottle",
        material: "en:glass",
        materialName: "Glass",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:cap",
        shapeName: "Cap (Capsule)",
        material: "en:metal",
        materialName: "Metal",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "glass_jar_metal_lid",
    title: "Glass Jar + Lid",
    description: "Jams, honey, pasta sauce, pickles, spreads",
    emoji: "🫙",
    badge: "Jams & Sauces",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:jar",
        shapeName: "Jar (Bocal)",
        material: "en:glass",
        materialName: "Glass",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:lid",
        shapeName: "Lid (Couvercle)",
        material: "en:metal",
        materialName: "Metal",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "can_metal",
    title: "Alu / Steel Can",
    description: "Soda cans, beer cans, canned fish, vegetables",
    emoji: "🥫",
    badge: "Cans",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:can",
        shapeName: "Can (Canette / Boîte)",
        material: "en:aluminium",
        materialName: "Aluminium",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "box_plastic_bag",
    title: "Cardboard Box + Plastic Bag",
    description: "Breakfast cereals, cookies, crackers, frozen meals",
    emoji: "📦",
    badge: "Cereals & Biscuits",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:box",
        shapeName: "Box (Étui / Boîte)",
        material: "en:cardboard",
        materialName: "Cardboard",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:bag",
        shapeName: "Bag / Wrapper",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "yogurt_pot_seal",
    title: "Yogurt Pot + Seal",
    description: "Yogurts, cream desserts, compote pots",
    emoji: "🥛",
    badge: "Dairy & Desserts",
    components: [
      {
        numberOfUnits: 4,
        shape: "en:pot",
        shapeName: "Pot",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 4,
        shape: "en:seal",
        shapeName: "Seal (Opercule)",
        material: "en:aluminium",
        materialName: "Aluminium",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "tetra_pak_cap",
    title: "Tetra Brik + Cap",
    description: "Milk cartons, fruit juices, liquid cream, soup",
    emoji: "🧃",
    badge: "Brik cartons",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:carton",
        shapeName: "Brik / Carton",
        material: "en:tetra-pak",
        materialName: "Tetra Pak",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
      {
        numberOfUnits: 1,
        shape: "en:cap",
        shapeName: "Cap",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "snack_bag",
    title: "Plastic Bag / Pouch",
    description: "Potato chips, candy, pasta, rice, frozen vegetables",
    emoji: "🛍️",
    badge: "Chips & Snacks",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:bag",
        shapeName: "Bag / Sachet",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
  {
    id: "chocolate_bar",
    title: "Chocolate Wrapper",
    description: "Chocolate tablets, cereal bars",
    emoji: "🍫",
    badge: "Chocolate",
    components: [
      {
        numberOfUnits: 1,
        shape: "en:wrapper",
        shapeName: "Wrapper",
        material: "en:plastic",
        materialName: "Plastic",
        recycling: "en:recycle",
        recyclingName: "Recycle",
      },
    ],
  },
];
