export const UNITS = ["", "g", "mg", "µg"];

export const KNOWN_NUTRIMENTS = [
  // Energy
  "energy-kj",
  "energy-kcal",

  // Fat
  "fat",
  "saturated-fat",
  "unsaturated-fat",
  "monounsaturated-fat",
  "polyunsaturated-fat",
  "trans-fat",
  "butyric-acid",
  "caproic-acid",
  "caprylic-acid",
  "capric-acid",
  "lauric-acid",
  "myristic-acid",
  "palmitic-acid",
  "stearic-acid",
  "arachidic-acid",
  "behenic-acid",
  "lignoceric-acid",
  "cerotic-acid",
  "montanic-acid",
  "melissic-acid",

  // Sucres
  "carbohydrates",
  "sugars",
  "added-sugars",
  "sucrose",
  "glucose",
  "fructose",
  "lactose",
  "maltose",
  "maltodextrins",

  "fiber",
  "soluble-fiber",
  "insoluble-fiber",

  "proteins",
  "casein",
  "serum-proteins",

  "salt",
  "added-salt",
  "sodium",

  "cholesterol",

  "alpha-linolenic-acid",
  "eicosapentaenoic-acid",
  "docosahexaenoic-acid",
  "omega-3-fat",
  "omega-6-fat",
  "linoleic-acid",
  "arachidonic-acid",
  "gamma-linolenic-acid",
  "dihomo-gamma-linolenic-acid",
  "omega-9-fat",
  "oleic-acid",
  "elaidic-acid",
  "gondoic-acid",
  "mead-acid",
  "erucic-acid",
  "nervonic-acid",

  "oligosaccharide",

  "galactose",
  "starch",
  "Polydextrose",
  "polyols",
  "erythritol",

  "nucleotides",
  "alcohol",
  "vitamin-a",
  "beta-carotene",
  "vitamin-d",
  "vitamin-e",
  "vitamin-k",
  "vitamin-c",
  "vitamin-b1",
  "vitamin-b2",
  "vitamin-pp",
  "vitamin-b6",
  "vitamin-b9",
  "folates",
  "vitamin-b12",
  "biotin",
  "pantothenic-acid",
  "silica",
  "bicarbonate",
  "sulphate",
  "nitrate",
  "nydrogencarbonate",
  "nitrite",
  "potassium",
  "chloride",
  "calcium",
  "phosphorus",
  "iron",
  "magnesium",
  "zinc",
  "copper",
  "manganese",
  "fluoride",
  "selenium",
  "chromium",
  "molybdenum",
  "iodine",
  "caffeine",
  "taurine",
  "ph",
  "collagen-meat-protein-ratio",
  "cocoa",
  "chlorophyl",
  "glycemic-index",
  "water-hardness",
  "choline",
  "phylloquinone",
  "beta-glucan",
  "inositol",
  "carnitine",
  "spermidine",
  "water",
  "acidity",
  "dry-residue",
  "beta-alanine",
  "creatine",
  "l-citrulline",
  "l-glutamine",
  "bcaa",
  "l-valine",
  "l-leucine",
  "l-isoleucine",
  "l-arginine",
  "l-cysteine",
  "l-Glutathione",
];
