const basicNutriments = [
  {
    off_nutriment_id: "energy-kj",
    label: "nutriment_energy-kj",
    value: "",
    unit: null,
    quantification: "=",
    robotoffPrediction: null,
    display: true,
    unitOptions: [],
  },
  {
    off_nutriment_id: "energy-kcal",
    label: "nutriment_energy-kcal",
    value: "",
    unit: null,
    quantification: "<",
    robotoffPrediction: null,
    display: true,
    unitOptions: [],
  },
  {
    off_nutriment_id: "nutriment_fat",
    label: "nutriment_fat",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: true,
  },
  {
    off_nutriment_id: "saturated-fat",
    label: "nutriment_saturated-fat",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: true,
  },
  {
    off_nutriment_id: "carbohydrates",
    label: "nutriment_carbohydrates",
    value: "",
    unit: "g",
    quantification: "=",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "sugars",
    label: "nutriment_sugars",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "proteins",
    label: "nutriment_proteins",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "fiber",
    label: "nutriment_fiber",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "salt",
    label: "nutriment_salt",
    value: "",
    unit: "g",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "sodium",
    label: "nutriment_sodium",
    value: "",
    unit: null,
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "zinc",
    label: "nutriment_zinc",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "vitamin-c",
    label: "nutriment_vitamin-c",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "vitamin-d",
    label: "nutriment_vitamin-d",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "vitamin-k",
    label: "nutriment_vitamin-k",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "vitamin-b6",
    label: "nutriment_vitamin-b6",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "vitamin-a",
    label: "nutriment_vitamin-a",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "selenium",
    label: "nutriment_selenium",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "bicarbonate",
    label: "nutriment_bicarbonate",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "magnesium",
    label: "nutriment_magnesium",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "pantothenic-acid",
    label: "nutriment_pantothenic-acid",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "fluoride",
    label: "nutriment_fluoride",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "iodine",
    label: "nutriment_iodine",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "silica",
    label: "nutriment_silica",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "alcohol",
    label: "nutriment_alcohol",
    value: "",
    unit: "% vol",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "potassium",
    label: "nutriment_potassium",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "manganese",
    label: "nutriment_manganese",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "phosphorus",
    label: "nutriment_phosphorus",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "biotin",
    label: "nutriment_biotin",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
  {
    off_nutriment_id: "ph",
    label: "nutriment_ph",
    value: "",
    unit: null,
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "molybdenum",
    label: "nutriment_molybdenum",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "caffeine",
    label: "nutriment_caffeine",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "chromium",
    label: "nutriment_chromium",
    value: "",
    unit: "µg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "iron",
    label: "nutriment_iron",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "copper",
    label: "nutriment_copper",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },

  {
    off_nutriment_id: "cholesterol",
    label: "nutriment_cholesterol",
    value: "",
    unit: "mg",
    quantification: "<",
    robotoffPrediction: null,
    display: false,
  },
];

export { basicNutriments };
